import dbConnect from "./db";
import Property from "../models/Property";
import Admin from "@/models/admin";
import bcrypt from "bcryptjs";

const adminDetails = {
  name: "Satish Yadav",
  email: "yadav.satish1232@gmail.com",
  password: await bcrypt.hash("yadav_admin_123", 10),
};

const sampleProperties = [
  // Properties for Sale
  {
    title: "Luxury 3BHK Apartment in Downtown Mumbai",
    description:
      "Beautiful apartment with modern amenities, located in the heart of Mumbai. Features include a gym, swimming pool, garden, and 24/7 security. Perfect for families looking for luxury living in a prime location.",
    price: 25000000,
    priceType: "sale",
    currency: "INR",
    location: "Bandra West",
    city: "Mumbai",
    state: "Maharashtra",
    address: "123 Bandra West, Mumbai, Maharashtra",
    bedrooms: 3,
    bathrooms: 2,
    area: 1850,
    areaUnit: "sq ft",
    propertyType: "apartment",
    status: "available",
    featured: true,
    images: ["/property-1.jpg", "/property-1-2.jpg", "/property-1-3.jpg"],
    amenities: ["Gym", "Pool", "Garden", "Security", "Parking", "Lift"],
    parking: true,
    furnished: true,
    readyToMove: true,
    yearBuilt: 2020,
    floor: 15,
    totalFloors: 25,
    contactPerson: "PropertyHub",
    contactPhone: "+91 99999 00000",
    contactEmail: "info@propertyhub.com",
    createdBy: "admin",
  },
  {
    title: "Beautiful Villa with Private Pool",
    description:
      "Spacious villa with private pool and garden, perfect for families. Features include a private swimming pool, landscaped garden, security system, and ample parking space.",
    price: 85000000,
    priceType: "sale",
    currency: "INR",
    location: "Whitefield",
    city: "Bangalore",
    state: "Karnataka",
    address: "456 Whitefield, Bangalore, Karnataka",
    bedrooms: 4,
    bathrooms: 3,
    area: 2400,
    areaUnit: "sq ft",
    propertyType: "villa",
    status: "available",
    featured: true,
    images: ["/property-2.jpg", "/property-2-2.jpg", "/property-2-3.jpg"],
    amenities: [
      "Private Pool",
      "Garden",
      "Security",
      "Parking",
      "Servant Quarters",
    ],
    parking: true,
    furnished: false,
    readyToMove: true,
    yearBuilt: 2018,
    floor: 1,
    totalFloors: 2,
    contactPerson: "PropertyHub",
    contactPhone: "+91 99999 00000",
    contactEmail: "info@propertyhub.com",
    createdBy: "admin",
  },
  {
    title: "Modern Office Space in Tech Park",
    description:
      "Professional office space in a modern tech park with all amenities. Perfect for startups and established companies looking for premium office space in a tech hub.",
    price: 12000000,
    priceType: "sale",
    currency: "INR",
    location: "Cyber City",
    city: "Gurgaon",
    state: "Haryana",
    address: "789 Cyber City, Gurgaon, Haryana",
    bedrooms: 0,
    bathrooms: 2,
    area: 3200,
    areaUnit: "sq ft",
    propertyType: "commercial",
    status: "available",
    featured: false,
    images: ["/property-3.jpg", "/property-3-2.jpg"],
    amenities: [
      "24/7 Security",
      "Parking",
      "Cafeteria",
      "Conference Rooms",
      "High-Speed Internet",
    ],
    parking: true,
    furnished: false,
    readyToMove: true,
    yearBuilt: 2022,
    floor: 8,
    totalFloors: 20,
    contactPerson: "PropertyHub",
    contactPhone: "+91 99999 00000",
    contactEmail: "info@propertyhub.com",
    createdBy: "admin",
  },
  {
    title: "Premium Penthouse with City View",
    description:
      "Luxury penthouse with panoramic city views and premium amenities. Features include a private terrace, city skyline views, luxury finishes, and exclusive access to building amenities.",
    price: 58000000,
    priceType: "sale",
    currency: "INR",
    location: "Jubilee Hills",
    city: "Hyderabad",
    state: "Telangana",
    address: "321 Jubilee Hills, Hyderabad, Telangana",
    bedrooms: 3,
    bathrooms: 3,
    area: 2800,
    areaUnit: "sq ft",
    propertyType: "penthouse",
    status: "available",
    featured: true,
    images: ["/property-4.jpg", "/property-4-2.jpg", "/property-4-3.jpg"],
    amenities: [
      "City View",
      "Luxury Amenities",
      "Gym",
      "Pool",
      "Private Terrace",
      "Security",
    ],
    parking: true,
    furnished: true,
    readyToMove: true,
    yearBuilt: 2021,
    floor: 25,
    totalFloors: 30,
    contactPerson: "PropertyHub",
    contactPhone: "+91 99999 00000",
    contactEmail: "info@propertyhub.com",
    createdBy: "admin",
  },
  {
    title: "Family Home with Garden",
    description:
      "Beautiful family home with spacious garden and modern amenities. Perfect for families who want space, privacy, and a connection to nature while staying in the city.",
    price: 32000000,
    priceType: "sale",
    currency: "INR",
    location: "Koregaon Park",
    city: "Pune",
    state: "Maharashtra",
    address: "654 Koregaon Park, Pune, Maharashtra",
    bedrooms: 3,
    bathrooms: 2,
    area: 1900,
    areaUnit: "sq ft",
    propertyType: "house",
    status: "available",
    featured: false,
    images: ["/property-5.jpg", "/property-5-2.jpg"],
    amenities: ["Garden", "Security", "Parking", "Servant Quarters"],
    parking: true,
    furnished: false,
    readyToMove: true,
    yearBuilt: 2019,
    floor: 1,
    totalFloors: 2,
    contactPerson: "PropertyHub",
    contactPhone: "+91 99999 00000",
    contactEmail: "info@propertyhub.com",
    createdBy: "admin",
  },

  // Properties for Rent
  {
    title: "Furnished 2BHK in Prime Location",
    description:
      "Beautiful furnished apartment with modern amenities, located in a prime area. Perfect for professionals or small families looking for a comfortable living space.",
    price: 45000,
    priceType: "rent",
    currency: "INR",
    location: "Bandra West",
    city: "Mumbai",
    state: "Maharashtra",
    address: "123 Bandra West, Mumbai, Maharashtra",
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    areaUnit: "sq ft",
    propertyType: "apartment",
    status: "available",
    featured: true,
    images: ["/property-6.jpg", "/property-6-2.jpg"],
    amenities: ["Furnished", "Gym", "Pool", "Security", "Parking"],
    parking: true,
    furnished: true,
    readyToMove: true,
    yearBuilt: 2020,
    floor: 12,
    totalFloors: 20,
    contactPerson: "PropertyHub",
    contactPhone: "+91 99999 00000",
    contactEmail: "info@propertyhub.com",
    createdBy: "admin",
  },
  {
    title: "Spacious Family Villa with Garden",
    description:
      "Large villa perfect for families with garden space. Features include a private garden, ample parking, and a peaceful environment away from the city hustle.",
    price: 85000,
    priceType: "rent",
    currency: "INR",
    location: "Whitefield",
    city: "Bangalore",
    state: "Karnataka",
    address: "456 Whitefield, Bangalore, Karnataka",
    bedrooms: 4,
    bathrooms: 3,
    area: 2400,
    areaUnit: "sq ft",
    propertyType: "villa",
    status: "available",
    featured: true,
    images: ["/property-7.jpg", "/property-7-2.jpg"],
    amenities: [
      "Private Pool",
      "Garden",
      "Security",
      "Parking",
      "Servant Quarters",
    ],
    parking: true,
    furnished: false,
    readyToMove: true,
    yearBuilt: 2018,
    floor: 1,
    totalFloors: 2,
    contactPerson: "PropertyHub",
    contactPhone: "+91 99999 00000",
    contactEmail: "info@propertyhub.com",
    createdBy: "admin",
  },
  {
    title: "Modern Studio in Tech Hub",
    description:
      "Contemporary studio apartment in tech hub area. Perfect for young professionals or students looking for modern, compact living space.",
    price: 25000,
    priceType: "rent",
    currency: "INR",
    location: "Cyber City",
    city: "Gurgaon",
    state: "Haryana",
    address: "789 Cyber City, Gurgaon, Haryana",
    bedrooms: 1,
    bathrooms: 1,
    area: 650,
    areaUnit: "sq ft",
    propertyType: "studio",
    status: "available",
    featured: false,
    images: ["/property-8.jpg", "/property-8-2.jpg"],
    amenities: ["Modern Kitchen", "Security", "Parking", "High-Speed Internet"],
    parking: false,
    furnished: true,
    readyToMove: true,
    yearBuilt: 2022,
    floor: 15,
    totalFloors: 25,
    contactPerson: "PropertyHub",
    contactPhone: "+91 99999 00000",
    contactEmail: "info@propertyhub.com",
    createdBy: "admin",
  },
  {
    title: "Luxury Penthouse with Amenities",
    description:
      "Premium penthouse with luxury amenities and city views. Perfect for executives or families who want the best of luxury living.",
    price: 120000,
    priceType: "rent",
    currency: "INR",
    location: "Golf Course Road",
    city: "Gurgaon",
    state: "Haryana",
    address: "321 Golf Course Road, Gurgaon, Haryana",
    bedrooms: 3,
    bathrooms: 2,
    area: 2200,
    areaUnit: "sq ft",
    propertyType: "penthouse",
    status: "available",
    featured: true,
    images: ["/property-9.jpg", "/property-9-2.jpg"],
    amenities: [
      "Luxury Amenities",
      "Gym",
      "Pool",
      "City View",
      "Security",
      "Parking",
    ],
    parking: true,
    furnished: true,
    readyToMove: true,
    yearBuilt: 2020,
    floor: 28,
    totalFloors: 30,
    contactPerson: "PropertyHub",
    contactPhone: "+91 99999 00000",
    contactEmail: "info@propertyhub.com",
    createdBy: "admin",
  },
  {
    title: "Cozy 1BHK Near Metro",
    description:
      "Cozy apartment near metro station with all basic amenities. Perfect for working professionals who want convenience and comfort.",
    price: 18000,
    priceType: "rent",
    currency: "INR",
    location: "Koregaon Park",
    city: "Pune",
    state: "Maharashtra",
    address: "654 Koregaon Park, Pune, Maharashtra",
    bedrooms: 1,
    bathrooms: 1,
    area: 550,
    areaUnit: "sq ft",
    propertyType: "apartment",
    status: "available",
    featured: false,
    images: ["/property-10.jpg", "/property-10-2.jpg"],
    amenities: ["Near Metro", "Security", "Basic Amenities"],
    parking: false,
    furnished: false,
    readyToMove: true,
    yearBuilt: 2018,
    floor: 8,
    totalFloors: 15,
    contactPerson: "PropertyHub",
    contactPhone: "+91 99999 00000",
    contactEmail: "info@propertyhub.com",
    createdBy: "admin",
  },
  {
    title: "Serviced Apartment with Gym",
    description:
      "Fully serviced apartment with gym facilities and daily housekeeping. Perfect for business travelers or professionals who want hassle-free living.",
    price: 65000,
    priceType: "rent",
    currency: "INR",
    location: "Jubilee Hills",
    city: "Hyderabad",
    state: "Telangana",
    address: "987 Jubilee Hills, Hyderabad, Telangana",
    bedrooms: 2,
    bathrooms: 2,
    area: 1400,
    areaUnit: "sq ft",
    propertyType: "apartment",
    status: "available",
    featured: false,
    images: ["/property-11.jpg", "/property-11-2.jpg"],
    amenities: ["Gym", "Serviced", "Security", "Parking", "Housekeeping"],
    parking: true,
    furnished: true,
    readyToMove: true,
    yearBuilt: 2021,
    floor: 18,
    totalFloors: 25,
    contactPerson: "PropertyHub",
    contactPhone: "+91 99999 00000",
    contactEmail: "info@propertyhub.com",
    createdBy: "admin",
  },
];

export async function seedDatabase() {
  try {
    await dbConnect();

    await Admin.deleteMany({});
    await Admin.create(adminDetails);

    await Property.deleteMany({});

    const result = await Property.insertMany(sampleProperties);

    return result;
  } catch (error) {
    console.error("Error seeding database:", error);
    throw error;
  }
}

if (require.main === module) {
  seedDatabase()
    .then(() => {
      console.log("Database seeding completed");
      process.exit(0);
    })
    .catch((error) => {
      console.error("Database seeding failed:", error);
      process.exit(1);
    });
}
